language: go
sudo: false

os:
  - linux
  - windows

go:
  - "1.14"
  - "1.15"
  - "1.16"

before_install:
  - go get github.com/mattn/goveralls
  - go mod vendor

script:
  - $GOPATH/bin/goveralls -service=travis-ci -race -show -package github.com/go-cmd/cmd
